name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 8 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: fjuniorr/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=fjuniorr/${{ github.event.repository.name }}:latest
        cache-to: type=inline
    - name: ETL pipeline
      run: docker run --rm --mount type=bind,source=${PWD},target=/project fjuniorr/${{ github.event.repository.name }} make all
    - name: Publish data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make publish
